[workspace]
authors = ["Julian Hofer <julianhofer@gnome.org>"]
channels = ["https://prefix.dev/conda-forge"]
name = "julianhofer.eu"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
serve = "zola serve"

[dependencies]
zola = ">=0.20.0,<0.21"
